// <auto-generated />
using BookManagerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagerAPI.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250505185657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagerAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Miles Kelly",
                            Price = 250.00m,
                            Title = "Encyclopedia Of Life"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Roald Dahl",
                            Price = 345.68m,
                            Title = "Matilda"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Jeff Kinney",
                            Price = 199.99m,
                            Title = "Diary of a Wimpy Kid"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Jannie Putter",
                            Price = 189.50m,
                            Title = "Secrets of a Champion"
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Lauren Kate",
                            Price = 225.75m,
                            Title = "Fallen"
                        },
                        new
                        {
                            BookID = 6,
                            Author = "Jeff Kinney",
                            Price = 210.00m,
                            Title = "Diary of a Wimpy Kid: Rodrick Rules"
                        },
                        new
                        {
                            BookID = 7,
                            Author = "Jeff Kinney",
                            Price = 205.50m,
                            Title = "Diary of a Wimpy Kid: The Last Straw"
                        },
                        new
                        {
                            BookID = 8,
                            Author = "Jeff Kinney",
                            Price = 215.75m,
                            Title = "Diary of a Wimpy Kid: Dog Days"
                        },
                        new
                        {
                            BookID = 9,
                            Author = "Friedrich Nietzsche",
                            Price = 310.99m,
                            Title = "The Birth of Tragedy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
